
server:
  error:
    include-binding-errors: always


logging:
  level:
    org.flywaydb: DEBUG

spring:
  application:
    name: CRMforDelivery
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: codekitchen
    password: 12345678

    hikari:
      maximum-pool-size: 8
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version:
    baseline-description: Initial baseline
    locations: classpath:db/migration

api:
  couriers:
    base: /api/couriers
  orders:
    base: /api/orders
  customers:
    base: /api/customers



jwt:
  access-token-key: '{"kty":"oct","k":"hi7S5RX5ZRZooHA0RKGctZ-KtR9FoESgCnH-3BNg5XI"}'
  refresh-token-key: '{"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}'
